artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://drive.google.com/file/d/1n5q946zaHqUxjAil7vZf_5MtNqbKuCvB/view?usp=sharing'
  local_data_file: artifacts/data_ingestion/data.rar
  unzip_dir: artifacts/data_ingestion
